apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.names.serviceName }}
  namespace: {{ .Values.namespace }} 
  labels:
    owner: valerii-vasianovych
    env: {{ .Values.label.env }}

spec:
  selector:
    app: {{ .Values.names.appName }}
  ports:
     - name: app-listener
       protocol: TCP
       port: 80
       targetPort: 80
  type: LoadBalancer