---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
   name: nginx
   region: us-east-1

vpc:
   id: vpc_id
   subnets:
      public:
         us-east-1a:
            id: subnet-id
         us-east-1b:
            id: subnet-id

nodeGroups:
   - name: worker-node-group-1
     instanceType: t2.micro
     desiredCapacity: 1
     subnets:
        - us-east-1a
     ssh:
        publicKeyName: ServersKey
   - name: worker-node-group-2
     instanceType: t2.micro
     desiredCapacity: 1
     subnets:
        - us-east-1b
     ssh:
        publicKeyName: ServersKey
