# Service configuration
apiVersion: v1
kind: Service
metadata:
   name: nginx-service-web1
   labels:
      app: nginx-web1
      env: dev
spec:
   selector:
      app: nginx-web1
   ports:
      - protocol: TCP
        port: 80
        targetPort: 80
   type: ClusterIP
