apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
   name: nginx-cluster
   region: us-east-1

vpc:
   id: your-vpc-id
   subnets:
      public:
         us-east-1a:
            id: your-subnet-id
         us-east-1b:
            id: your-subnet-id

nodeGroups:
   - name: worker-node-group-1
     instanceType: t2.micro
     desiredCapacity: 1
     ssh:
        publicKeyName: ServersKey
     subnets:
        - your-subnet-id
   - name: worker-node-group-2
     instanceType: t2.micro
     desiredCapacity: 1
     ssh:
        publicKeyName: ServersKey
     subnets:
        - your-subnet-id
