apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
   name  : spring-boot-cluster
   region: us-east-1

nodeGroups:
   - name           : worker-node-group-1
     instanceType   : t2.micro
     desiredCapacity: 2
     ssh:
         publicKeyName: ServersKey
