apiVersion: v1
kind: Service
metadata:
  name: my-prometheus-server
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/instance: my-prometheus
    component: server
  ports:
    - port: 80
      targetPort: 9090
      protocol: TCP
      name: http
