apiVersion: v1
kind: Service
metadata:
  name: httpd-service
  labels:
    owner: valerii-vasianovych
    env: dev

spec:
  selector:
    app: httpd
  ports:
     - name: app-listener
       protocol: TCP
       port: 80
       targetPort: 80
  type: LoadBalancer