apiVersion: v1
kind: Pod
metadata:
   name: nginx-pod
   labels:
      app: nginx
      env: test
      tier: frontend
      owner: ValeriiVasianovych
spec:
   containers:
      - name: nginx-container
        image: nginx:latest
        ports:
           - containerPort: 80
